### ISSUE TITLE
Security Risk: When initializing the database connection, the connection string is logged which will display database user name and password in the log file 

### ISSUE THREAD

**Issue by OmnicellMike** [wcabus/DapperContext#2]
There is a big security risk when initializing. The constructor allows for the database connect string to connect to the database. When the connection to SQL is successful it logs the connection string which can contain the database user name and password. If the password exists in the connection string is should not be added to the logging or at least don't display that actual password in the log.

**Comment by wcabus** [comment]
Thanks for reporting this. I looked into the issue, and I'm pretty certain that I never expose the actual connection string. There's no logging integrated in this library, I can only assume that you're concerned about https://github.com/wcabus/DapperContext/blob/master/DapperContext.NET35/DbConnectionFactory.cs#L31 where the `ConfigurationErrorsException` is thrown. I only expose the name of the connection string, not the connection string itself.
